### ISSUE TITLE
Permission Support

### ISSUE THREAD

**Issue by Jakingtosch** [NathanWolf/MagicPlugin#1]
Like it´s said,

please implement Permissions support (or is it implemented but not just mentioned?)

**Comment by NathanWolf** [comment]
Permissions has been provided in Spells/Wand via PermissionsSupport.jar

If Magic ever gets finished, it will probably _not_ support Permissions, but rather Bukkit's internal permissions system, which I expect to be released "any day now" (just like Magic!)
