### ISSUE TITLE
Spell use/upgrades not saved on logout 

### ISSUE THREAD

**Issue by SmallSansSerif** [NathanWolf/MagicPlugin#2]
So just noticed this today after looking at spell upgrade npc today. If you want to level up a spell it would seem that all 50 uses need to come during 1 online session. If you relog the counter appears to reset to 0. Is that normal behavior? 

It seems like it should keep spell uses stored for each user even if they use in multiple sessions, right?

Thanks in advance.

**Comment by NathanWolf** [comment]
It is supposed to save it! You're finding that it's not? I'll test that right away.

Also, if you could please check your logs for any errors- I have been trying to track down an occasional error saving player data, but it seems to work most of the time.

**Comment by SmallSansSerif** [comment]
I haven't noticed anything in the logs but I will look again.. No error messages that I see. You can test on my server by trying to level some spells.. click on the NPC and it shows them going up .. relog and they are set back to 0.

**Comment by SmallSansSerif** [comment]
Oops looks like I posted this on wrong Github home too..

**Comment by NathanWolf** [comment]
Oh- heh sure enough :) This was the original codebase before I forked it into an org so (optimistically) other dev could work on it.

Anyway, I just tried it myself locally and it happened immediately. Thanks for pointing this out before I release 4.9.3, this is a pretty bad issue. I've noticed that the data is saving, but somehow getting lost on load- hopefully I can find an easy fix!

**Comment by NathanWolf** [comment]
Fixed in 4.9.3 - thanks! :)

**Comment by SmallSansSerif** [comment]
Woo hoo .. great!

Hey, would that explain why some wands keep losing their glow?

**Comment by NathanWolf** [comment]
No, that's a completely separate issue. Mainly that Spigot/Craftbukkit don't really support adding glow to items, so it may randomly lose its glow. I think the wand does try to re-instate it occasionally, but honestly I gave up on that fight :)
